[package]
name = "zkb"
version = "0.1.0"
authors = ["seb_odessa<seb_odessa@example.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "lib"
path = "src/lib/lib.rs"

[[bin]]
name = "zkb"
path = "src/main.rs"

[dependencies]
    serde = { version = "1.0", features = ["derive"]}
    serde_json = "*"
    diesel = {version = "1.4", features = ["sqlite"]}
    diesel_codegen = "0.16"
    dotenv = "0.10"


